---
title: "Instituto Nacional de Ciência e Tecnologia das Radiações na Saúde"
subtitle: "INTERAS"
---

Novas tecnologias para caracterização rápida, não-invasiva e de baixo custo para doenças, são decisivas na diminuição da mortalidade, o que ficou evidenciado durante a pandemia. Aos desafios na detecção precoce e no tratamento do câncer, somaram-se questões relacionadas ao surgimento de novos vírus com alta taxa de letalidade, como o SARS-CoV-2. Tratamentos clínicos avançaram exponencialmente nas últimas décadas, mas podem ser caros e ineficazes. O INTERA se propõe desenvolver e aplicar métodos diagnósticos e terapêuticos numa ampla diversidade de doenças (cânceres, doenças cardíacas e cardiorenais, infecções virais, doenças negligenciadas) assistidos por radiações em ampla faixa do espectro eletromagnético. O IPEN é o caso mais bem sucedido de inovação translacional, levando a hospitais e clínicas os produtos e processos desenvolvidos desde a pesquisa básica, na área de radiofármacos, desde sua criaçao em 1956. Os objetivos específicos compreendem o desenvolvimento de novos radiofármacos baseados em anticorpos para diagnóstico por imagem PET/SPECT, radioterapia alvo-dirigida de tumores, nanobraquiterapia, processos terapêuticos com lasers, diagnóstico de diferentes doenças por imagem hiperespectral no infravermelho e raman, avaliados por inteligência artificial. Pretende-se executar a translação não apenas para clínica, mas principalmente para o setor produtivo. Estamos fortemente convencidos que o estabelecimento de um diagnóstico e terapia médica de precisão e personalizada é um dos grandes desafios da medicina moderna que o INTERAS também poderá resolver criando um mosaico científico-industrial. Para isto, apresentamos proposta transdisciplinar com mais de 30 pesquisadores de 8 Instituições (AM, PE, SP, RJ e SE) e colaboradores internacionais e nacionais. Vale ressaltar, que os pesquisadores do INTERAS possuem uma alta inserção acadêmica e industrial. Propomos ainda implementar um diálogo contínuo com a sociedade por meio de ações de divulgação científica.

 

Instituições participantes Nacionais:

  1. Instituto de Pesquisas Energéticas e Nucleares - Executora/Sede
  2. Universidade Federal do ABC - Laboratório Associado
  3. Universidade Federal do Rio de Janeiro - Laboratório Associado
  4. Universidade Federal de Sergipe - Laboratório Associado
  5.  Universidade Federal de Uberlândia  - Laboratório Associado
  6. Universidade de São Paulo  (FOUSP e FFCLRP, Ribeirão Preto) - Laboratório Associado
  7. Universidade Federal de São Paulo - Laboratório Associado
  8. Instituto do Câncer do Estado de São Paulo - Octávio Frias de Oliveira - Laboratório Associado
  9. Centro Regional de Ciências Nucleares do Nordeste - Laboratório Associado

Instituições participantes estrangeiras:

* University of Wisconsin - Madison - WISCONSIN, United States
* Hôpital Universitaire Necker-Enfants Malades - NECKER, France
* Durham University - DURHAM, England
* Ruprecht-Karls-Universität Heidelberg - HEIDELBERG, Germany
* University of Exeter - EXETER, England
* Universidad Autónoma de Madrid - UAM, Spain
* University of St Andrews - ST-ANDREWS, Scotland

 

Empresas:

* Revolugenix Biotecnologia, Pesquisa e Desenvolvimento Ltda - SP, Brazil
* BRVANT e IBRV - Instituto de Pesquisa e Desenvolvimento - IBRV, SP, Brazil
* ANACOM Científica
* AXCEM Dermatologia
* Biolambda, Científica e Comercial Ltda
* Clean Clinica Especializada em Anatomia Oral S/C 
* CK Estomatologia S/C Ltda
* Curitiba Biotecnologia - Curitiba Biotech, PR, Brazil
* LM Insight Ltda
